version: '3.4'

services:  
  mariadb:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: blog-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${GHOST_DB_CONN_USER}
      MYSQL_PASSWORD: ${GHOST_DB_CONN_PASSWORD}
      MYSQL_DATABASE: ${GHOST_DB_CONN_DB}
    restart: always
    volumes:
      - ${MARIADB_DATA_PATH}:/var/lib/mysql

  ghost:
    image: ghost:${GHOST_IMAGE_TAG}
    container_name: blog-ghost
    environment:
      url: ${GHOST_BLOG_URL}
      database__client: ${GHOST_DB_CLIENT}
      database__connection__host: ${GHOST_DB_CONN}
      database__connection__database: ${GHOST_DB_CONN_DB}
      database__connection__user: ${GHOST_DB_CONN_USER}
      database__connection__password: ${GHOST_DB_CONN_PASSWORD}
      mail_from: ${GHOST_MAIL_FROM}
      mail__transport: ${GHOST_MAIL_TRANSPORT}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASSWORD}
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ${GHOST_CONTENT_PATH}:/var/lib/ghost/content

  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: blog-nginx
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_WWWW_ROOT_PATH}:/var/www/html
      - ${CERTBOT_CONF_PATH}:/etc/nginx/ssl
      - ${CERTBOT_DATA_PATH}:/var/www/certbot

  certbot:
    image: certbot/certbot:${CERTBOT_IMAGE_TAG}
    container_name: blog-certbot
    command: certonly --noninteractive --expand --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN} -d ${CERTBOT_SUB_DOMAIN}
    volumes:
      - ${CERTBOT_CONF_PATH}:/etc/letsencrypt
      - ${CERTBOT_LOG_PATH}:/var/log/letsencrypt
      - ${CERTBOT_DATA_PATH}:/var/www/certbot

  remark42:
    # build: .
    image: umputun/remark42:v1.8.1
    container_name: blog-remark42
    hostname: remark42
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    # uncomment to expose directly (no proxy)
    # ports:
    #   - "80:8080"

    environment:
      - REMARK_URL=https://erturk.me/remark42
      - SITE=erturk.me
      - SECRET=xxxxxxxx
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - DEBUG=true
      - ADMIN_PASSWD=xxx
      - AUTH_GITHUB_CID=7e6021dc2b32bb9d133c
      - AUTH_GITHUB_CSEC=d9a7e6b915a8638ec84cdba7f557350435094e5d
      # - AUTH_GOOGLE_CID=xxxxxxxx
      # - AUTH_GOOGLE_CSEC=xxxxxxxx
      # - AUTH_EMAIL_ENABLE=true
      # - AUTH_EMAIL_HOST=smtp.mailgun.org
      # - AUTH_EMAIL_PORT=465
      # - AUTH_EMAIL_FROM=noreply@mail.devbitsandbytes.com
      # - AUTH_EMAIL_SUBJ=remark42 confirmation
      # - AUTH_EMAIL_CONTENT_TYPE=text/html
      # - AUTH_EMAIL_TLS=true
      # - AUTH_EMAIL_USER=postmaster@mail.devbitsandbytes.com
      # - AUTH_EMAIL_PASSWD=xxxxxxxx
      # - AUTH_EMAIL_TIMEOUT=10s
      # - ADMIN_SHARED_EMAIL=support@devbitsandbytes.com #where Admin related emails need to be sent
      # - NOTIFY_EMAIL_ADMIN=true
      # - NOTIFY_EMAIL_FROM=noreply@mail.devbitsandbytes.com
      # - SMTP_HOST=smtp.mailgun.org
      # - SMTP_PORT=465
      # - SMTP_TLS=true
      # - SMTP_USERNAME=postmaster@mail.devbitsandbytes.com
      # - SMTP_PASSWORD=xxxxxxxx
      # - NOTIFY_USERS=email
      # - NOTIFY_ADMINS=email
      # - NOTIFY_TYPE=email
    volumes:
      - ./remark42:/srv/var
