version: '3.4'

services:  
  mariadb:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: blog-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${GHOST_DB_CONN_USER}
      MYSQL_PASSWORD: ${GHOST_DB_CONN_PASSWORD}
      MYSQL_DATABASE: ${GHOST_DB_CONN_DB}
    restart: always
    volumes:
      - ${MARIADB_DATA_PATH}:/var/lib/mysql

  ghost:
    image: ghost:${GHOST_IMAGE_TAG}
    container_name: blog-ghost
    environment:
      url: ${GHOST_BLOG_URL}
      database__client: ${GHOST_DB_CLIENT}
      database__connection__host: ${GHOST_DB_CONN}
      database__connection__database: ${GHOST_DB_CONN_DB}
      database__connection__user: ${GHOST_DB_CONN_USER}
      database__connection__password: ${GHOST_DB_CONN_PASSWORD}
      mail_from: ${GHOST_MAIL_FROM}
      mail__transport: ${GHOST_MAIL_TRANSPORT}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASSWORD}
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ${GHOST_CONTENT_PATH}:/var/lib/ghost/content

  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: blog-nginx
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/default.conf
      - ${NGINX_WWWW_ROOT_PATH}:/var/www/html
      - ${CERTBOT_CONF_PATH}:/etc/nginx/ssl
      - ${CERTBOT_DATA_PATH}:/var/www/certbot

  certbot:
    image: certbot/certbot:${CERTBOT_IMAGE_TAG}
    container_name: blog-certbot
    command: certonly --noninteractive --expand --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN} -d ${CERTBOT_SUB_DOMAIN}
    volumes:
      - ${CERTBOT_CONF_PATH}:/etc/letsencrypt
      - ${CERTBOT_LOG_PATH}:/var/log/letsencrypt
      - ${CERTBOT_DATA_PATH}:/var/www/certbot

  remark42:
    # build: .
    image: umputun/remark42:${REMARK42_IMAGE_TAG}
    container_name: blog-remark42
    hostname: remark42
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - REMARK_URL=${REMARK42_REMARK_URL}
      - SITE=${REMARK42_SITE}
      - SECRET=${REMARK42_SECRET}
      - STORE_BOLT_PATH=${REMARK42_STORE_BOLT_PATH}
      - BACKUP_PATH=${REMARK42_BACKUP_PATH}
      - DEBUG=${REMARK42_DEBUG}
      - ADMIN_PASSWD=${REMARK42_ADMIN_PASSWD}
      - AUTH_GITHUB_CID=${REMARK42_AUTH_GITHUB_CID}
      - AUTH_GITHUB_CSEC=${REMARK42_AUTH_GITHUB_CSEC}
      - AUTH_FACEBOOK_CID=${REMARK42_AUTH_FACEBOOK_CID}
      - AUTH_FACEBOOK_CSEC=${REMARK42_AUTH_FACEBOOK_CSEC}
      # - AUTH_TWITTER_CID=${}
      # - AUTH_TWITTER_CSEC=${}
      - AUTH_EMAIL_ENABLE=${REMARK42_AUTH_EMAIL_ENABLE}
      - AUTH_EMAIL_FROM=${REMARK42_AUTH_EMAIL_FROM}
      - AUTH_EMAIL_SUBJ=${REMARK42_AUTH_EMAIL_SUBJ}
      - AUTH_EMAIL_CONTENT_TYPE=${REMARK42_AUTH_EMAIL_CONTENT_TYPE}
      - ADMIN_SHARED_EMAIL=${REMARK42_ADMIN_SHARED_EMAIL}
      - NOTIFY_EMAIL_FROM=${REMARK42_NOTIFY_EMAIL_FROM}
      - SMTP_HOST=${REMARK42_SMTP_HOST}
      - SMTP_PORT=${REMARK42_SMTP_PORT}
      - SMTP_TLS=${REMARK42_SMTP_TLS}
      - SMTP_TIMEOUT=${REMARK42_SMTP_TIMEOUT}
      - SMTP_USERNAME=${REMARK42_SMTP_USERNAME}
      - SMTP_PASSWORD=${REMARK42_SMTP_PASSWORD}
      - NOTIFY_USERS=${REMARK42_NOTIFY_USERS}
      - NOTIFY_ADMINS=${REMARK42_NOTIFY_ADMINS}
      # - AUTH_ANON=${REMARK42_AUTH_ANON}
      # - ANON_VOTE=${REMARK42_ANON_VOTE}
    volumes:
      - ${REMARK42_HOST_PATH}:/srv/var
