version: '3.4'

services:  
  mariadb:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: blog-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${GHOST_DB_CONN_USER}
      MYSQL_PASSWORD: ${GHOST_DB_CONN_PASSWORD}
      MYSQL_DATABASE: ${GHOST_DB_CONN_DB}
    restart: always
    volumes:
      - ${MARIADB_DATA_PATH}:/var/lib/mysql

  ghost:
    image: ghost:${GHOST_IMAGE_TAG}
    container_name: blog-ghost
    environment:
      url: ${GHOST_BLOG_URL}
      database__client: ${GHOST_DB_CLIENT}
      database__connection__host: ${GHOST_DB_CONN}
      database__connection__database: ${GHOST_DB_CONN_DB}
      database__connection__user: ${GHOST_DB_CONN_USER}
      database__connection__password: ${GHOST_DB_CONN_PASSWORD}
      mail_from: ${GHOST_MAIL_FROM}
      mail__transport: ${GHOST_MAIL_TRANSPORT}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASSWORD}
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ${GHOST_CONTENT_PATH}:/var/lib/ghost/content

  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: blog-nginx
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_WWWW_ROOT_PATH}:/var/www/html
      - ${CERTBOT_CONF_PATH}:/etc/nginx/ssl
      - ${CERTBOT_DATA_PATH}:/var/www/certbot

  certbot:
    image: certbot/certbot:${CERTBOT_IMAGE_TAG}
    container_name: blog-certbot
    command: certonly --noninteractive --expand --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN} -d ${CERTBOT_SUB_DOMAIN}
    volumes:
      - ${CERTBOT_CONF_PATH}:/etc/letsencrypt
      - ${CERTBOT_LOG_PATH}:/var/log/letsencrypt
      - ${CERTBOT_DATA_PATH}:/var/www/certbot
